name: Publish

on:
  push:
    branches:
        - kp-publish

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        sudo apt-get install -y python3-setuptools python3-venv
    - name: Build the docs
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        make vhtml
    - name: Pre-deploy
      run: |
        mv _build/html $HOME/output
    - name: Deploy the docs
      run: |
        cd $HOME/output
        git init
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@github.com"
        git add .
        git commit -m "latest html output"
        git push -f https://${GITHUB_ACTOR}:${{secrets.ACCESS_TOKEN}}@github.com/clearlinux/clear-linux-documentation.git HEAD:gh-pages