name: Publish

on:
  push:
    branches:
        - kp-publish

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-venv
    - uses: actions/checkout@v2
      with:
        ref: devel
    - name: Build latest
      run: |
        make vhtml
        mv _build/html $HOME/output
    - name: Deploy the docs
      run: |
        cd $HOME/output
        git init
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@github.com"
        git add .
        git commit -m "latest html output"
        git push -f https://${GITHUB_ACTOR}:${{secrets.ACCESS_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git HEAD:gh-pages